### PR TITLE
Replace cli.Context with app.CliContext

### LINKED ISSUE #53: Add go api for creating a http server

### LINKED ISSUE #54: Remove cli.Context as global dependency

### PR DESCRIPTION
**Pull request by SimonBaeumer**
fixes #54 
fixes #53

### CODE REVIEW

**Comment by au-phiware** [comment]
Certainly, this is a nice explaination: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

That article sites this one as the source of the idea: https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html?m=1

**Comment by SimonBaeumer** [comment]
Very good article, I like the idea and will try to implement it.

**Comment by SimonBaeumer** [comment]
@au-phiware Yeah, continued development and tried the `WithOptions`.
The `WithOptions` way is very nice but for this case it added too much overhead to create all these functions (and variadic functions are a little bit annoying in a process where a method`s input params change every minute^^) 
For now I added some more structs as you suggested, and it worked very very well:

- `GossRunTime` in `app.go`, should hold global available config. Furhter it is the go-api which will be used a single point to access all main goss features like validating. The naming is a little bit bad because the actual test suite (content inside the `goss.yaml`) is called `GossConfig`.
- `HealthHandler` in `serve.go`, just rewrote the original struct a little bit and made `Serve` a method on `HealthHandler`.
- `Validator` in `validate.go`. Just moved the input parameters to the struct.
- The `app.CliContext` will be deleted step-by-step, for the refactoring process it is 1 Million times better than the `urfave/cli.Context`

It now makes it already easier to debug. There are still a lot of flaws which need to be removed/changed. 
The next step is to move the properties to their correct responsibilities, i.e. `Package` should be moved from `GossRunTime` to the `package` resource. This will make the structs and method signatures a lot easier.

Maybe you find time for a little bit feedback! :+1:

**Comment by au-phiware** [comment]
This sounds great. You are right, the `WithOption` is better suited to
options the change infrequently or only in edge case scenarios. I'll try to
take a look at the code tomorrow, but sounds like you've made some good
progress.

**Pull request merged**
